# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b47b29f67bd9587091687185851334cc28d4d3a7cca12903857fc268e7edf5fe2f7d4b899fe150cbc1fd29e6f3b474d67adbc632135af0872af0dbb7035f034b

test:
  secret_key_base: 9f560279a7bcf7a7e0dd2ed8a8feca9c86e486c7816c370c2eb6ca8568e521357fd65359b09e65e31582188e2e06ee0c5e205df6a90248c39c4a9687653e9d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
